# Generated by Django 5.2.7 on 2025-10-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='inventario_producto',
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, unique=True, verbose_name='Código de lote')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'db_table': 'inventario_existencia',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
