# Generated by Django 5.2.7 on 2025-10-21 21:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por kg (COP)'),
        ),
    ]
