# Generated by Django 5.2.7 on 2025-10-23 23:12

import datetime
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_existencia_fecha_ingreso_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2025, 10, 23), verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='fecha_vencimiento',
            field=models.DateField(default=inventario.models.default_fecha_vencimiento, verbose_name='Fecha de vencimiento'),
        ),
    ]
