# Generated by Django 5.2.7 on 2025-10-23 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_existencia_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso'),
        ),
    ]
